package com.example.weather.utils

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.platform.LocalConfiguration
import java.util.*

object StringResources {
    private val strings = mapOf(
        "ru" to mapOf(
            "welcome" to "Добро пожаловать",
            "lets_start_journey" to "Начнем путешествие",
            "collection_description" to "Умная, великолепная и модная коллекция Изучите сейчас",
            "you_have_power" to "У вас есть сила, чтобы",
            "plants_description" to "В вашей комнате много красивых и привлекательных растений",
            "hello" to "Привет!",
            "fill_details" to "Заполните Свои данные Или Продолжите Через Социальные Медиа",
            "email" to "Email",
            "password" to "Пароль",
            "register" to "Регистрация",
            "your_name" to "Ваше имя",
            "agree_to_terms" to "Даю согласие на обработку персональных данных",
            "sign_up" to "Зарегистрироваться",
            "sign_in" to "Войти",
            "create_account" to "Вы впервые? Создать пользователя",
            "have_account" to "Есть аккаунт? Войти",
            "recover" to "Воcстановить",
            "forgot_password" to "Забыл пароль",
            "enter_account" to "Введите свою учетную запись для сброса",
            "send" to "Отправить",
            "check_email" to "Проверьте Ваш Email",
            "recovery_code_sent" to "Мы отправили код восстановления пароля на вашу электронную почту.",
            "otp_verification" to "OTP проверка",
            "check_email_verification" to "Пожалуйста, проверьте свою электронную почту, чтобы увидеть код подтверждения",
            "otp_code" to "OTP Код",
            "home" to "Главная",
            "search" to "Поиск",
            "categories" to "Категории",
            "popular" to "Популярное",
            "all" to "Все",
            "promotions" to "Акции",
            "favorite" to "Избранное",
            "cart" to "Корзина",
            "items" to "товара",
            "subtotal" to "Сумма",
            "delivery" to "Доставка",
            "total" to "Итого",
            "checkout" to "Оформить заказ",
            "contact_info" to "Контактная информация",
            "address" to "Адрес",
            "payment_method" to "Способ оплаты",
            "min_ago" to "мин назад",
            "open" to "Открыть",
            "view_map" to "Посмотреть на карте",
            "recent" to "Недавний",
            "yesterday" to "Вчера",
            "add_to_cart" to "В корзину",
            "payment_successful" to "Вы успешно оформили заказ",
            "back_to_shopping" to "Вернуться к покупкам",
            "orders" to "Заказы",
            "notifications" to "Уведомления",
            "settings" to "Настройки",
            "sign_out" to "Выйти",
            "change_profile_photo" to "Изменить фото профиля",
            "first_name" to "Имя",
            "last_name" to "Фамилия",
            "save" to "Сохранить"
        ),
        "en" to mapOf(
            "welcome" to "Welcome",
            "lets_start_journey" to "Let's Start Journey",
            "collection_description" to "Smart, Gorgeous & Fashionable Collection Explor Now",
            "you_have_power" to "You Have the Power To",
            "plants_description" to "There Are Many Beautiful And Attractive Plants To Your Room",
            "hello" to "Hello Again!",
            "fill_details" to "Fill your details or continue with social media",
            "email" to "Email Address",
            "password" to "Password",
            "register" to "Register Account",
            "your_name" to "Your Name",
            "agree_to_terms" to "I agree to the processing of personal data",
            "sign_up" to "Sign up",
            "sign_in" to "Sign In",
            "create_account" to "New User? Create Account",
            "have_account" to "Already Have Account? Log In",
            "recover" to "Recovery Password",
            "forgot_password" to "Forgot Password",
            "enter_account" to "Enter your Email account to reset your password",
            "send" to "Send",
            "check_email" to "Check your email",
            "recovery_code_sent" to "We have send password recovery code in your email",
            "otp_verification" to "OTP Verification",
            "check_email_verification" to "Please check your email to see the verification code",
            "otp_code" to "OTP Code",
            "home" to "Explore",
            "search" to "Looking for shoes",
            "categories" to "Select Category",
            "popular" to "Popular Shoes",
            "all" to "See all",
            "promotions" to "New Arrivals",
            "favorite" to "Favourite",
            "cart" to "CART",
            "items" to "Items",
            "subtotal" to "Subtotal",
            "delivery" to "Delivery",
            "total" to "Total Cost",
            "checkout" to "Checkout",
            "contact_info" to "Contact Information",
            "address" to "Address",
            "payment_method" to "Payment Method",
            "min_ago" to "min ago",
            "open" to "OPEN",
            "view_map" to "View Map",
            "recent" to "Recent",
            "yesterday" to "Yesterday",
            "add_to_cart" to "Add to Cart",
            "payment_successful" to "Your Payment Is Successful",
            "back_to_shopping" to "Back To Shopping",
            "orders" to "Orders",
            "notifications" to "Notifications",
            "settings" to "SETTINGS",
            "sign_out" to "Sign Out",
            "change_profile_photo" to "Change Profile Picture",
            "first_name" to "Your Name",
            "last_name" to "Last Name",
            "save" to "save Now"
        )
    )

    @Composable
    @ReadOnlyComposable
    fun getString(key: String): String {
        val locale = LocalConfiguration.current.locales[0]
        val language = locale.language.lowercase(Locale.getDefault())
        return strings[language]?.get(key) ?: strings["en"]?.get(key) ?: key
    }
} 